"""
Django settings for bookmanager project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# __file__：当前文件的文件名（settings.py）
# Path(__file__)：当前文件的绝对路径 （D:\typora_synchronous\BaiduSyncdisk\python_script\Practice_items\django开发\code\bookmanager\bookmanager\settings.py）
# BASE_DIR： 当前文件父目录的父目录 （D:\typora_synchronous\BaiduSyncdisk\python_script\Practice_items\django开发\code\bookmanager）
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-az6p*6for*l_(i6vp$-u+j8@)rnmi0x*plcz=^v80-my*#l&od'

# SECURITY WARNING: don't run with debug turned on in production!
# 开发调试用debug模式，正式部署上线需要关闭False
DEBUG = True

# 安全机制，相当于白名单：允许主机ip、域名访问后端，默认是120.0.0.1
ALLOWED_HOSTS = ["192.168.31.75", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',  # 使用jinja2需要注释掉所有django默认模板的admin后台相关代码
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',  # Session数据存储在数据库中，需要在项INSTALLED_APPS中安装Session应用
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 添加新的子项目
    'book.apps.BookConfig'
]

# 中间件
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',  # 默认启用Session，注释则关闭
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',  # CSRF防护，默认开启，测试时可以关闭CSRF防护机制
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 注册中间件
    # 执行顺序：请求的时候是按照从上往下的顺序，响应的时候是按照从下往上的顺序
    'book.middleware.my_middleware1',  # 添加中间件 my_middleware1
    'book.middleware.my_middleware2',  # 添加中间件 my_middleware2
]

# 工程的url配置入口，默认是工程名.urls
ROOT_URLCONF = 'bookmanager.urls'

# 模板相关的配置信息
TEMPLATES = [
    {
        # 'BACKEND': 'django.template.backends.django.DjangoTemplates',  # django自带的模板引擎
        'BACKEND': 'django.template.backends.jinja2.Jinja2',  # 修改为jinja2模板引擎
        'DIRS': [BASE_DIR / 'template'],  # 设置模板路径
        'APP_DIRS': True,
        'OPTIONS': {
            'environment': "bookmanager.jinja_env.environment",  # 指向新建的jinja_env.py文件中的environment函数
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bookmanager.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# sqlite 小型的关系型数据库，移动端使用
# mysql、sqlserver 中型的关系型数据库
# oracle、DB2 大型的关系型数据库
DATABASES = {
    'default': {
        # engine 引擎
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': BASE_DIR / 'db.sqlite3',
        'ENGINE': 'django.db.backends.mysql',
        'HOST': '127.0.0.1',  # 主机
        'PORT': '3306',  # 端口号
        'USER': 'root',  # 用户名
        'PASSWORD': 'tj000401', # 密码
        'NAME': 'books', # 指定数据库
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'  # 语言设置

TIME_ZONE = 'Asia/Shanghai'  # 时区设置

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

# django通过STATIC_URL区分是静态资源（http://ip:prot/STATIC_URL/文件名）
STATIC_URL = '/static/'

# 静态文件路径
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
